version: 2.1

jobs:
  auto-create-config:
    docker:
      - image: circleci/config-setup:latest
    steps:
      - checkout
      - run:
          name: Generate Config
          command: config-setup generate-and-add-config << pipeline.id >>

workflows:
  generate-config:
    jobs:
      - auto-create-config